export const enum LogConstant {
  LOG_KEY_ID = "_id",
  LOG_KEY_ACTION = "action",
  LOG_KEY_STATUS = "status",
  LOG_KEY_JOBCOUNT = "jobCount",
  LOG_KEY_HOSTINFO = "hostInfo",
  LOG_KEY_CREATEDAT = "createdAt",
  LOG_KEY_RESOURCEID = "resourceId",
  LOG_KEY_DESCRIPTION = "description",
  LOG_KEY_ERROWMESSAGE = "errorMessage",
  LOG_HOST_KEY_SKU = "sku",
  LOG_HOST_KEY_LOCATION = "location",
  LOG_HOST_KEY_OLDNAME = "oldHostName",
  LOG_HOST_KEY_NEWNAME = "newHostName",
}
